### ISSUE TITLE
Error: 'firebase' is not exported by src/firebase.js

### ISSUE THREAD

**Issue by ekafyi** [Yarrney/sapper-tailwind-firebase-host#3]
I cloned this repo and did not change anything other than replacing the firebaseConfig and collection name with my own.

When i run `npm run dev`, I got the error `'firebase' is not exported by src/firebase.js`.

```
✗ client
'firebase' is not exported by src/firebase.js
3:   // import login from '../components/login.svelte';
4:   import { onMount } from "svelte";
5:   import { firebase } from "./../firebase";
              ^
6:   let image = "undraw_to_the_moon_v1.svg";
7:   export let list = [];
```

I used different code from https://github.com/sveltecasts/009-sapper-firestore that did what I needed. Just posting this as a heads up.

**Comment by Yarrney** [comment]
Ah! Thank you for the heads up - I'll have a look into it and get back to you! Glad to hear the sveltecasts template works for you though!

**Comment by Yarrney** [comment]
This was my fault - rookie error.  I was using this same repo to develop a "feature" - being connecting to the firebase auth service - only later to realise the whole point of an SSR app is to pre-render content primarily for better speed but secondly for enhanced SEO - which (generally) runs at counter to having an app with auth.  That being said, I'm sure there are occasions which having both SSR and Auth are handy, but just not in the projects I've been working on!
